.Informations générales
[format="csv"]
|======================
Rédacteur, K3rn€l P4n1k
Date, Sat Jan 19 10:36:51 CET 2019
État, Rédigé
|======================

# DIARY

.Objectif du document
Documente l'usage du script du journal.

.Description générale
Diary est un système de prise de note en ligne de commande.
Les notes prises sont chiffrées.

.Intention
Prendre des notes à la volée sans avoir à sortir de la console.

## Dépendences

.Liste des dépendences
[format="csv", options="header"]
|====
Description, Dépendences, Téléchargement
Chiffrement, openssl, 
|====

## Usage


### Création d'une note

.Usage
[source, bash]
----
diary.new <topic> <note>
----

.Arguments
[format="csv"]
|====
`topic`, catégorie utilisé pour classer la note
`note`, contenu de la note
|====

.Exemple
[source, bash]
----
diary.new activité "en train d'ecrire de la doc"
diary.new humeur ":)"
----

.Résultat
----
➜  ~ diary.new activité "en train d'écrire de la doc"
2019-01-19  10:50:41  #activité  en train d'écrire de la doc

➜  ~ diary.new humeur ":)"
2019-01-19  10:50:41  #activité  en train d'écrire de la doc
2019-01-19  10:51:02  #humeur    :)
----

### Consultation de l'historique

.Usage
[source, bash]
----
diary.history
----

.Exemple
[source, bash]
----
diary.history
----

.Résultat
----
➜  ~ diary.history
2019-01-19  10:51:02  #humeur     :)
2019-01-19  10:50:41  #activité   en train d'écrire de la doc
----

## Installation

Il est nécessaire de créer la variable `${DIARY_KEY}` pour que les messages puissent être chiffrés 

## Commentaires

Les notes sont stockés en csv, séparateur `;`

.Raccourcis
[source, bash]
----
alias @humeur='diary.new humeur'
alias @idée='diary.new idée'
alias @reflexion='diary.new reflexion'
alias @recherche='diary.new recherche'
alias @développement='diary.new développement'
alias @création='diary.new création'
alias @réussite='diary.new réussite'
alias @échec='diary.new échec'
----

